### ISSUE TITLE
[opinion] api 호출 - createRequest 이후의 promise 체이닝이 어려워 보임

### ISSUE THREAD

**Issue by chchoing88** [LeadJockey/vue-setting#1]
질문 : createRequest의 함수에서 Promise의 반환값이 없어서 onSuccess 이후의 체이닝이 안되어 보임
하여 클라이언트가 onSuccess 함수에 비동기 함수를 넣는다면 후속 조치가 어려워 보임

예상해 볼수 있는 상황 : 

```javascript
// 추가 비동기적 코드 작성
getCountData({ onSuccess: data => new Promise((resolve, reject) => {
  setTimeout(() => resolve(data), 3000) // 3초후에 data 반환
})})

// 3초 후에 commit('setCountAs', data.count) 를 하고 싶음..어떻게 해야할까.. 또는 클라이언트가 3초후에 에러가 났을때 후속조치를 어떻게 할 수 있을까.
```

> 다만 onSuccess 함수에 클라이언트가 async / await 함수나 자체적으로 promise/then 체이닝을 구현한다면 한다면 관계는 없어 보임. ( 이 사실을 알 사람이 많지 않을꺼 같긴한데... )

해결책 1. api 쪽 전반의 함수(successHandler, errorHandelr 까지도)에서 return 문이 필요해 보임. 최종적으로는 getCountData도 Promise를 반환하면 onSuccess 안에 Promise를 작성하는 것보다 getCountData에 이어서 then/catch 체이닝을 구사할수 있을 꺼 같음..

그런데 위 처럼 코드를 바꿔보면 
```javascript
getCountData(...).then().catch().. 
```
이런식으로 될 터인데 뭔가 문법적으로 통일감이 또 없어보이긴함...

느낌이 1차 비동기에 대해서는 onSuccess 같은걸로 내가 처리해줄께.. 하지만 그 뒤에 있는 Promise 들은 다시 Promise의 then이나 catch를 사용해 라는 느낌이 듬.

해결책 2. ㅋㅋ 모르겠뜸

**Comment by LeadJockey** [comment]
우선 관심을가지고 의견을 피력해 준것에 대해서 감사합니다 멀린!

src/api/index.js > createRequest 함수에 관하여...
* axios 의 인스턴스를 리턴함으로 체이닝이 가능하도록 하는것이 확장성에 도움이 될것으로 생각이 되어짐.
* 하지만 components 단위에서 handler의 로직을 바로 입력하는 것에 대해서는 회의적.
* handler 들을 따로 하나의 폴더에 모아서 관리하는것이 이상적이라고 판단됨.
